### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by MiguelArgentina**
The project lets us practice creating forms in Rails, and this will be achieved in two different ways:
 > The Forms will first be built using nearly-pure HTML
 >  After the first step, the Forms will be built using Rails helpers
 > Any additional instructions can be found in the Readme file

The goal is to compare the usefulness of Rails helpers to the pure HTML forms

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @MiguelArgentina and @george-swift    ! :wave: :wave:

#### You have done well so far, good job adding those styles :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.


**Recommended**

- [ ] Please fix your rubocop errors, most of which can be fixed by running `rubocop -a` in your terminal.
 
- [ ]  Views
- Commented out forms are missing. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form1.png) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_form2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by MiguelArgentina** [comment]
Rubocop tests don´t fail within the GitHub Actions but only fail locally because of corrections we made in the base to what Commit `d149156` tests asked us to do. Locally, the tests fail and ask to add the Frozen String Literal to all those files.
A screenshot of local Rubocop tests is attached below.

Screen Shot 2021-03-12 at 14 09 55

**Comment by MiguelArgentina** [comment]
In New and Edit Views, the `if false` condition encloses the unused forms and therefore comment out the block of code.
For example, you can see that on lines 15 and 28 of the New User view:

Screen Shot 2021-03-12 at 14 18 40

**Review by NtwaliHeritier — APPROVED** [review]
### **STATUS: APPROVED✔✔✔**
Hello @MiguelArgentina ,
This is a great project implementation. 
I like how you worked on it.
I see what you did with the commenting however you should use ruby's way of coding.
As I do not want to delay this PR, I will approve it but I will mark the commenting as optional.
Before merging, kindly comment out the codes using rails way.👍👍

Happy coding💻💻

**Pull request merged**
